# Generated by Django 5.0.7 on 2026-05-19 11:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base_data', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_no', models.CharField(max_length=32, unique=True, verbose_name='计划编号')),
                ('plan_type', models.CharField(choices=[('month', '月计划'), ('week', '周计划'), ('urgent', '急单')], max_length=16, verbose_name='计划类型')),
                ('plan_quantity', models.IntegerField(verbose_name='计划数量')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('approved', '已审批'), ('released', '已下发'), ('completed', '已完成'), ('cancelled', '已取消')], default='draft', max_length=16, verbose_name='状态')),
                ('scheduled_start', models.DateField(verbose_name='计划开始日期')),
                ('scheduled_end', models.DateField(verbose_name='计划结束日期')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='审批时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_plans', to=settings.AUTH_USER_MODEL, verbose_name='审批人')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_plans', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_plans', to='base_data.material', verbose_name='产品')),
            ],
            options={
                'verbose_name': '生产计划',
                'verbose_name_plural': '生产计划',
                'db_table': 'prod_plan',
                'ordering': ['-created_at'],
            },
        ),
    ]
