# Generated by Django 5.0.7 on 2026-05-19 11:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base_data', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='仓库名称')),
                ('code', models.CharField(max_length=16, unique=True, verbose_name='仓库编码')),
                ('warehouse_type', models.CharField(choices=[('raw', '原料仓'), ('finished', '成品仓'), ('spare', '备件仓')], default='raw', max_length=16, verbose_name='仓库类型')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('keeper', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouses', to=settings.AUTH_USER_MODEL, verbose_name='仓管员')),
            ],
            options={
                'verbose_name': '仓库',
                'verbose_name_plural': '仓库',
                'db_table': 'inv_warehouse',
            },
        ),
        migrations.CreateModel(
            name='InventoryTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_no', models.CharField(max_length=32, unique=True, verbose_name='流水号')),
                ('transaction_type', models.CharField(choices=[('purchase_in', '采购入库'), ('produce_in', '生产入库'), ('material_out', '原料出库'), ('sale_out', '销售出库'), ('return_in', '退货入库'), ('other', '其他')], max_length=16, verbose_name='交易类型')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='数量')),
                ('source_doc_type', models.CharField(blank=True, default='', max_length=32, verbose_name='来源单据类型')),
                ('source_doc_id', models.BigIntegerField(blank=True, null=True, verbose_name='来源单据ID')),
                ('remark', models.CharField(blank=True, default='', max_length=256, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='base_data.material', verbose_name='物料')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='inventory.warehouse', verbose_name='仓库')),
            ],
            options={
                'verbose_name': '库存流水',
                'verbose_name_plural': '库存流水',
                'db_table': 'inv_transaction',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, default='', max_length=64, verbose_name='库位')),
                ('quantity', models.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name='库存数量')),
                ('locked_quantity', models.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name='锁定数量')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='base_data.material', verbose_name='物料')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='inventory.warehouse', verbose_name='仓库')),
            ],
            options={
                'verbose_name': '库存',
                'verbose_name_plural': '库存',
                'db_table': 'inv_inventory',
                'ordering': ['material', 'warehouse', 'location'],
                'unique_together': {('material', 'warehouse', 'location')},
            },
        ),
    ]
