# Generated by Django 5.0.7 on 2026-05-19 11:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base_data', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionStandard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=64, verbose_name='检验项目')),
                ('standard_desc', models.TextField(verbose_name='标准描述')),
                ('tolerance', models.CharField(blank=True, default='', max_length=128, verbose_name='公差范围')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '检验标准',
                'verbose_name_plural': '检验标准',
                'db_table': 'qc_standard',
                'ordering': ['product', 'item_name'],
            },
        ),
        migrations.CreateModel(
            name='InspectionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_type', models.CharField(choices=[('in_process', '过程检'), ('final', '终检')], max_length=16, verbose_name='检验类型')),
                ('sample_quantity', models.IntegerField(verbose_name='抽检数量')),
                ('pass_quantity', models.IntegerField(verbose_name='合格数量')),
                ('defect_quantity', models.IntegerField(default=0, verbose_name='不良数量')),
                ('defect_details', models.JSONField(blank=True, help_text='格式: [{"defect_type": "缺陷类型", "count": 数量}]', null=True, verbose_name='不良明细')),
                ('result', models.CharField(choices=[('pass', '合格'), ('fail', '不合格'), ('concession', '让步接收')], max_length=16, verbose_name='检验结果')),
                ('report_no', models.CharField(max_length=32, verbose_name='报告编号')),
                ('inspected_at', models.DateTimeField(auto_now_add=True, verbose_name='检验时间')),
                ('inspector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inspections', to=settings.AUTH_USER_MODEL, verbose_name='检验员')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inspections', to='base_data.material', verbose_name='产品')),
            ],
            options={
                'verbose_name': '检验记录',
                'verbose_name_plural': '检验记录',
                'db_table': 'qc_record',
                'ordering': ['-inspected_at'],
            },
        ),
    ]
