# Generated by Django 5.0.7 on 2026-05-19 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base_data', '0001_initial'),
        ('quality', '0001_initial'),
        ('work_order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectionrecord',
            name='work_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspections', to='work_order.workorder', verbose_name='工单'),
        ),
        migrations.AddField(
            model_name='inspectionstandard',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspection_standards', to='base_data.material', verbose_name='产品'),
        ),
    ]
