# Generated by Django 5.0.7 on 2026-05-19 11:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('base_data', '0001_initial'),
        ('prod_plan', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wo_no', models.CharField(max_length=32, unique=True, verbose_name='工单号')),
                ('order_quantity', models.IntegerField(verbose_name='订单数量')),
                ('completed_quantity', models.IntegerField(default=0, verbose_name='完成数量')),
                ('defect_quantity', models.IntegerField(default=0, verbose_name='不良数量')),
                ('priority', models.CharField(choices=[('normal', '普通'), ('urgent', '紧急'), ('low', '低')], default='normal', max_length=8, verbose_name='优先级')),
                ('status', models.CharField(choices=[('pending', '待派工'), ('dispatched', '已派工'), ('in_progress', '生产中'), ('completed', '已完成'), ('closed', '已关闭')], default='pending', max_length=16, verbose_name='状态')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_orders_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_orders', to='base_data.material', verbose_name='产品')),
                ('production_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_orders', to='prod_plan.productionplan', verbose_name='生产计划')),
                ('route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_orders', to='base_data.route', verbose_name='工艺路线')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_orders', to='accounts.workshop', verbose_name='车间')),
            ],
            options={
                'verbose_name': '工单',
                'verbose_name_plural': '工单',
                'db_table': 'work_order',
                'ordering': ['-created_at'],
            },
        ),
    ]
