# Generated by Django 5.0.7 on 2026-05-19 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_code', models.CharField(max_length=64, unique=True, verbose_name='物料编码')),
                ('material_name', models.CharField(max_length=128, verbose_name='物料名称')),
                ('specification', models.CharField(blank=True, default='', max_length=256, verbose_name='规格型号')),
                ('unit', models.CharField(max_length=16, verbose_name='计量单位')),
                ('material_type', models.CharField(choices=[('raw', '原材料'), ('semi', '半成品'), ('finished', '成品')], max_length=16, verbose_name='物料类型')),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='单位成本')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '物料',
                'verbose_name_plural': '物料',
                'db_table': 'base_material',
            },
        ),
        migrations.CreateModel(
            name='BOMItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='用量')),
                ('unit', models.CharField(max_length=16, verbose_name='单位')),
                ('process_step', models.IntegerField(blank=True, null=True, verbose_name='工序序号')),
                ('child_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bom_parents', to='base_data.material', verbose_name='子物料')),
                ('parent_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bom_children', to='base_data.material', verbose_name='父物料')),
            ],
            options={
                'verbose_name': 'BOM明细',
                'verbose_name_plural': 'BOM明细',
                'db_table': 'base_bom_item',
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_name', models.CharField(max_length=128, verbose_name='工艺路线名称')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='base_data.material', verbose_name='产品')),
            ],
            options={
                'verbose_name': '工艺路线',
                'verbose_name_plural': '工艺路线',
                'db_table': 'base_route',
            },
        ),
        migrations.CreateModel(
            name='WorkCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='工作中心名称')),
                ('code', models.CharField(max_length=32, unique=True, verbose_name='工作中心编码')),
                ('capacity_per_day', models.IntegerField(default=0, verbose_name='日产能')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_centers', to='accounts.workshop', verbose_name='所属车间')),
            ],
            options={
                'verbose_name': '工作中心',
                'verbose_name_plural': '工作中心',
                'db_table': 'base_work_center',
            },
        ),
        migrations.CreateModel(
            name='RouteStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_no', models.IntegerField(verbose_name='工序序号')),
                ('step_name', models.CharField(max_length=128, verbose_name='工序名称')),
                ('standard_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='标准工时(小时)')),
                ('description', models.TextField(blank=True, default='', verbose_name='工序说明')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='base_data.route', verbose_name='工艺路线')),
                ('work_center', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='route_steps', to='base_data.workcenter', verbose_name='工作中心')),
            ],
            options={
                'verbose_name': '工艺路线工序',
                'verbose_name_plural': '工艺路线工序',
                'db_table': 'base_route_step',
                'ordering': ['route', 'step_no'],
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='设备名称')),
                ('code', models.CharField(max_length=32, unique=True, verbose_name='设备编码')),
                ('model', models.CharField(blank=True, default='', max_length=128, verbose_name='设备型号')),
                ('status', models.CharField(choices=[('normal', '正常'), ('maintenance', '维修中'), ('scrapped', '已报废')], default='normal', max_length=16, verbose_name='设备状态')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='购置日期')),
                ('work_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipments', to='base_data.workcenter', verbose_name='所属工作中心')),
            ],
            options={
                'verbose_name': '设备',
                'verbose_name_plural': '设备',
                'db_table': 'base_equipment',
            },
        ),
    ]
