# Generated by Django 5.0.7 on 2026-05-19 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_quantity', models.IntegerField(verbose_name='合格数量')),
                ('defect_quantity', models.IntegerField(default=0, verbose_name='不良数量')),
                ('work_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='工时')),
                ('report_time', models.DateTimeField(auto_now_add=True, verbose_name='报工时间')),
                ('remark', models.CharField(blank=True, default='', max_length=512, verbose_name='备注')),
                ('route_step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_reports', to='base_data.routestep', verbose_name='工艺步骤')),
            ],
            options={
                'verbose_name': '工作报工',
                'verbose_name_plural': '工作报工',
                'db_table': 'prod_work_report',
                'ordering': ['-report_time'],
            },
        ),
    ]
