# Generated by Django 5.0.7 on 2026-05-19 11:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('prod_track', '0001_initial'),
        ('work_order', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='workreport',
            name='work_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_reports', to='work_order.workorder', verbose_name='工单'),
        ),
        migrations.AddField(
            model_name='workreport',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_reports', to=settings.AUTH_USER_MODEL, verbose_name='工人'),
        ),
    ]
