# Generated by Django 5.0.7 on 2026-05-19 11:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base_data', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_code', models.CharField(max_length=64, unique=True, verbose_name='客户编码')),
                ('customer_name', models.CharField(max_length=128, verbose_name='客户名称')),
                ('contact_person', models.CharField(blank=True, default='', max_length=64, verbose_name='联系人')),
                ('contact_phone', models.CharField(blank=True, default='', max_length=32, verbose_name='联系电话')),
                ('address', models.CharField(blank=True, default='', max_length=256, verbose_name='地址')),
                ('customer_level', models.CharField(choices=[('A', 'A级'), ('B', 'B级'), ('C', 'C级')], default='C', max_length=1, verbose_name='客户等级')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '客户',
                'verbose_name_plural': '客户',
                'db_table': 'biz_customer',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_code', models.CharField(max_length=64, unique=True, verbose_name='供应商编码')),
                ('supplier_name', models.CharField(max_length=128, verbose_name='供应商名称')),
                ('contact_person', models.CharField(blank=True, default='', max_length=64, verbose_name='联系人')),
                ('contact_phone', models.CharField(blank=True, default='', max_length=32, verbose_name='联系电话')),
                ('supply_category', models.CharField(blank=True, default='', max_length=128, verbose_name='供货类别')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '供应商',
                'verbose_name_plural': '供应商',
                'db_table': 'biz_supplier',
            },
        ),
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_no', models.CharField(max_length=64, unique=True, verbose_name='销售订单号')),
                ('order_quantity', models.IntegerField(verbose_name='订单数量')),
                ('delivered_quantity', models.IntegerField(default=0, verbose_name='已发货数量')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='单价')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='总金额')),
                ('scheduled_date', models.DateField(verbose_name='计划交付日期')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('approved', '已审批'), ('in_production', '生产中'), ('shipped', '已发货'), ('completed', '已完成'), ('cancelled', '已取消')], default='draft', max_length=16, verbose_name='状态')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='审批时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_orders_approved', to=settings.AUTH_USER_MODEL, verbose_name='审批人')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_orders_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_orders', to='business.customer', verbose_name='客户')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_orders', to='base_data.material', verbose_name='产品')),
                ('sales_person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_orders_person', to=settings.AUTH_USER_MODEL, verbose_name='业务员')),
            ],
            options={
                'verbose_name': '销售订单',
                'verbose_name_plural': '销售订单',
                'db_table': 'biz_sales_order',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_no', models.CharField(max_length=64, unique=True, verbose_name='采购订单号')),
                ('order_quantity', models.IntegerField(verbose_name='订单数量')),
                ('received_quantity', models.IntegerField(default=0, verbose_name='已收货数量')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='单价')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='总金额')),
                ('ordered_date', models.DateField(verbose_name='下单日期')),
                ('expected_date', models.DateField(verbose_name='预计到货日期')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('approved', '已审批'), ('ordered', '已下单'), ('partial_received', '部分收货'), ('received', '已收货'), ('cancelled', '已取消')], default='draft', max_length=16, verbose_name='状态')),
                ('source_doc_type', models.CharField(blank=True, max_length=32, null=True, verbose_name='来源单据类型')),
                ('source_doc_id', models.BigIntegerField(blank=True, null=True, verbose_name='来源单据ID')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='审批时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders_approved', to=settings.AUTH_USER_MODEL, verbose_name='审批人')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to=settings.AUTH_USER_MODEL, verbose_name='采购员')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='base_data.material', verbose_name='物料')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='business.supplier', verbose_name='供应商')),
            ],
            options={
                'verbose_name': '采购订单',
                'verbose_name_plural': '采购订单',
                'db_table': 'biz_purchase_order',
                'ordering': ['-created_at'],
            },
        ),
    ]
